server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, loggers, beans
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    com.courseselling: DEBUG
