version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_SERVICE_DB_NAME}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - coursedb-net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - coursedb-net

  eureka-server:
    build: ./eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    networks:
      - coursedb-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  config-server:
    build: ./config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    depends_on:
      - eureka-server
    networks:
      - coursedb-net
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  user-management-service:
    build: ./user-management-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${USER_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${USER_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=user-management-service
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  course-management-service:
    build: ./course-management-service
    ports:
      - "${COURSE_SERVICE_PORT}:${COURSE_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${COURSE_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${COURSE_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${COURSE_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=course-management-service
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  enrollmentservice:
    build: ./enrollmentservice
    ports:
      - "${ENROLLMENT_SERVICE_PORT}:${ENROLLMENT_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${ENROLLMENT_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${ENROLLMENT_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ENROLLMENT_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=enrollmentservice
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  notification-service:
    build: ./notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${NOTIFICATION_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${NOTIFICATION_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${NOTIFICATION_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=notification-service
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  payment-service:
    build: ./payment
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${PAYMENT_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${PAYMENT_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PAYMENT_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=payment-service
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    networks:
      - coursedb-net

  content-delivery-service:
    build: ./content-delivery-service
    ports:
      - "${CONTENT_SERVICE_PORT}:${CONTENT_SERVICE_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${CONTENT_SERVICE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${CONTENT_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${CONTENT_SERVICE_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=content-delivery-service
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  actuator:
    build: ./actuator
    ports:
      - "${ACTUATOR_PORT}:${ACTUATOR_PORT}"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${ACTUATOR_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${ACTUATOR_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ACTUATOR_DB_PASSWORD}
      - SPRING_APPLICATION_NAME=actuator
      - SPRING_CONFIG_IMPORT=optional:configserver:${CONFIG_SERVER_URL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8765"
    depends_on:
      - user-management-service
      - course-management-service
      - enrollmentservice
      - notification-service
      - payment-service
      - content-delivery-service
      - actuator
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    networks:
      - coursedb-net

volumes:
  mysql-data:
  jenkins-data:

networks:
  coursedb-net:
