apiVersion: v1
kind: ConfigMap
metadata:
  name: actuator-config
  namespace: course-plat
data:
  SPRING_APPLICATION_NAME: "actuator"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuator
  namespace: course-plat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actuator
  template:
    metadata:
      labels:
        app: actuator
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: actuator
        image: DOCKERHUB_USER/course-plat-actuator:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - configMapRef:
            name: actuator-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: actuator
  namespace: course-plat
spec:
  selector:
    app: actuator
  ports:
  - port: 8081
    targetPort: 8081
    name: http

