apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: course-plat
data:
  SPRING_PROFILES_ACTIVE: "git"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: course-plat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: config-server
        image: DOCKERHUB_USER/course-plat-config-server:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: http
        - containerPort: 8081
          name: metrics
        envFrom:
        - configMapRef:
            name: config-server-config
        env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: course-plat
spec:
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics

