apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
  namespace: course-platform
  labels:
    app: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: course-platform/course-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/course_platform"
        - name: SPRING_DATASOURCE_USERNAME
          value: "courseuser"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: REDIS_PORT
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: EUREKA_SERVER_URL
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: CONFIG_SERVER_URL
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: course-platform-config
              key: RABBITMQ_PORT
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /course-service/actuator/health
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /course-service/actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: course-platform
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP