apiVersion: v1
kind: ConfigMap
metadata:
  name: enrollment-service-config
  namespace: course-plat
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_APPLICATION_NAME: "enrollment-service"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/enrollment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
  namespace: course-plat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
      - name: wait-for-eureka
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka; sleep 2; done;']
      - name: wait-for-config
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting for config; sleep 2; done;']
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: enrollment-service
        image: DOCKERHUB_USER/course-plat-enrollment-service:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: http
        - containerPort: 8081
          name: metrics
        envFrom:
        - configMapRef:
            name: enrollment-service-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: course-plat
spec:
  selector:
    app: enrollment-service
  ports:
  - port: 8084
    targetPort: 8084
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics

