apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: course-plat
data:
  SPRING_PROFILES_ACTIVE: "docker"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: course-plat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: eureka-server
        image: DOCKERHUB_USER/course-plat-eureka-server:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
          name: http
        - containerPort: 8081
          name: metrics
        envFrom:
        - configMapRef:
            name: eureka-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: course-plat
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics

