apiVersion: v1
kind: Namespace
metadata:
  name: course-platform
  labels:
    name: course-platform
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: course-platform-config
  namespace: course-platform
data:
  # Database Configuration
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "course_platform"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  
  # Eureka Configuration
  EUREKA_SERVER_URL: "http://eureka-service:8761/eureka"
  
  # Config Server Configuration
  CONFIG_SERVER_URL: "http://config-server-service:8888"
  
  # API Gateway Configuration
  API_GATEWAY_URL: "http://api-gateway-service:8765"
  
  # Service Ports
  USER_SERVICE_PORT: "8082"
  COURSE_SERVICE_PORT: "8083"
  ENROLLMENT_SERVICE_PORT: "8084"
  NOTIFICATION_SERVICE_PORT: "8085"
  PAYMENT_SERVICE_PORT: "8086"
  CONTENT_SERVICE_PORT: "8087"
  CONFIG_SERVER_PORT: "8888"
  EUREKA_SERVER_PORT: "8761"
  API_GATEWAY_PORT: "8765"
  
  # Monitoring Configuration
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  
  # Application Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  LOGGING_LEVEL: "INFO"