global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'jenkins-alerts@company.com'
  smtp_auth_username: 'jenkins-alerts@company.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
  - match:
      service: jenkins
    receiver: 'jenkins-team'
    routes:
    - match:
        severity: critical
      receiver: 'jenkins-critical'
      group_wait: 0s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'jenkins-warnings'
      repeat_interval: 1h

receivers:
- name: 'default'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#general'
    title: 'Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'jenkins-team'
  email_configs:
  - to: 'jenkins-team@company.com'
    subject: 'Jenkins Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#jenkins-alerts'
    title: 'Jenkins Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

- name: 'jenkins-critical'
  email_configs:
  - to: 'jenkins-oncall@company.com'
    subject: 'CRITICAL Jenkins Alert: {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL ALERT - IMMEDIATE ACTION REQUIRED
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#jenkins-critical'
    title: '🚨 CRITICAL Jenkins Alert: {{ .GroupLabels.alertname }}'
    text: |
      <!channel> CRITICAL ALERT - IMMEDIATE ACTION REQUIRED
      
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}
    color: 'danger'
  # PagerDuty integration for critical alerts
  pagerduty_configs:
  - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
    description: 'Jenkins Critical Alert: {{ .GroupLabels.alertname }}'

- name: 'jenkins-warnings'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#jenkins-warnings'
    title: '⚠️ Jenkins Warning: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}
    color: 'warning'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

- source_match:
    alertname: 'JenkinsDown'
  target_match_re:
    alertname: 'Jenkins.*'
  equal: ['instance']