# Prometheus Alerting Rules for Jenkins
# This file contains comprehensive alerting rules for Jenkins monitoring

groups:
  - name: jenkins.alerts
    rules:
      # Jenkins Service Availability
      - alert: JenkinsDown
        expr: up{job="jenkins"} == 0
        for: 1m
        labels:
          severity: critical
          service: jenkins
          category: availability
        annotations:
          summary: "Jenkins is down"
          description: "Jenkins instance {{ $labels.instance }} has been down for more than 1 minute."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-down"
          dashboard_url: "http://grafana:3000/d/jenkins-overview"

      - alert: JenkinsHighResponseTime
        expr: jenkins_http_response_time_milliseconds > 5000
        for: 5m
        labels:
          severity: warning
          service: jenkins
          category: performance
        annotations:
          summary: "Jenkins high response time"
          description: "Jenkins instance {{ $labels.instance }} has response time > 5 seconds for {{ $value }}ms."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-performance"

      # Build Queue Alerts
      - alert: JenkinsBuildQueueHigh
        expr: jenkins_queue_size > 10
        for: 5m
        labels:
          severity: warning
          service: jenkins
          category: capacity
        annotations:
          summary: "Jenkins build queue is high"
          description: "Jenkins build queue has {{ $value }} items waiting for more than 5 minutes."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-queue"

      - alert: JenkinsBuildQueueCritical
        expr: jenkins_queue_size > 50
        for: 2m
        labels:
          severity: critical
          service: jenkins
          category: capacity
        annotations:
          summary: "Jenkins build queue is critically high"
          description: "Jenkins build queue has {{ $value }} items, indicating severe capacity issues."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-queue"

      - alert: JenkinsQueueStuck
        expr: increase(jenkins_queue_size[30m]) == 0 and jenkins_queue_size > 0
        for: 30m
        labels:
          severity: critical
          service: jenkins
          category: availability
        annotations:
          summary: "Jenkins queue appears stuck"
          description: "Jenkins queue size hasn't changed in 30 minutes with {{ $value }} items queued."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-stuck-queue"

      # Executor Alerts
      - alert: JenkinsExecutorsLow
        expr: (jenkins_executor_free / jenkins_executor_total) < 0.2
        for: 10m
        labels:
          severity: warning
          service: jenkins
          category: capacity
        annotations:
          summary: "Jenkins executors running low"
          description: "Less than 20% of Jenkins executors are available ({{ $value | humanizePercentage }})."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-executors"

      - alert: JenkinsNoFreeExecutors
        expr: jenkins_executor_free == 0
        for: 5m
        labels:
          severity: critical
          service: jenkins
          category: capacity
        annotations:
          summary: "No free Jenkins executors"
          description: "All Jenkins executors are busy. New builds will be queued."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-executors"

      # Node Alerts
      - alert: JenkinsNodeOffline
        expr: jenkins_node_online == 0
        for: 2m
        labels:
          severity: warning
          service: jenkins
          category: availability
        annotations:
          summary: "Jenkins node is offline"
          description: "Jenkins node {{ $labels.node }} has been offline for more than 2 minutes."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-node-offline"

      - alert: JenkinsNodeHighLoad
        expr: jenkins_node_load_average > 4
        for: 10m
        labels:
          severity: warning
          service: jenkins
          category: performance
        annotations:
          summary: "Jenkins node high load"
          description: "Jenkins node {{ $labels.node }} has high load average: {{ $value }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-node-performance"

      # Build Failure Alerts
      - alert: JenkinsHighFailureRate
        expr: (rate(jenkins_builds_failure_total[1h]) / rate(jenkins_builds_total[1h])) > 0.3
        for: 15m
        labels:
          severity: warning
          service: jenkins
          category: quality
        annotations:
          summary: "High Jenkins build failure rate"
          description: "Jenkins build failure rate is {{ $value | humanizePercentage }} over the last hour."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-build-failures"

      - alert: JenkinsCriticalJobFailing
        expr: jenkins_job_last_build_result{job=~".*production.*|.*deploy.*|.*release.*"} != 1
        for: 1m
        labels:
          severity: critical
          service: jenkins
          category: deployment
        annotations:
          summary: "Critical Jenkins job failing"
          description: "Critical job {{ $labels.job }} is failing or unstable."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-critical-job-failure"

      - alert: JenkinsJobNotRun
        expr: time() - jenkins_job_last_build_timestamp > 86400
        for: 1h
        labels:
          severity: warning
          service: jenkins
          category: monitoring
        annotations:
          summary: "Jenkins job hasn't run recently"
          description: "Job {{ $labels.job }} hasn't run in over 24 hours."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-job-not-running"

      # Disk Space Alerts
      - alert: JenkinsDiskSpaceLow
        expr: (jenkins_disk_usage_bytes / jenkins_disk_total_bytes) > 0.8
        for: 5m
        labels:
          severity: warning
          service: jenkins
          category: resources
        annotations:
          summary: "Jenkins disk space low"
          description: "Jenkins disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-disk-space"

      - alert: JenkinsDiskSpaceCritical
        expr: (jenkins_disk_usage_bytes / jenkins_disk_total_bytes) > 0.9
        for: 1m
        labels:
          severity: critical
          service: jenkins
          category: resources
        annotations:
          summary: "Jenkins disk space critically low"
          description: "Jenkins disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-disk-space"

      # Memory Alerts
      - alert: JenkinsHighMemoryUsage
        expr: (jenkins_memory_used_bytes / jenkins_memory_total_bytes) > 0.8
        for: 10m
        labels:
          severity: warning
          service: jenkins
          category: resources
        annotations:
          summary: "Jenkins high memory usage"
          description: "Jenkins memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-memory"

      - alert: JenkinsMemoryLeak
        expr: increase(jenkins_memory_used_bytes[1h]) > 1073741824  # 1GB increase
        for: 30m
        labels:
          severity: warning
          service: jenkins
          category: resources
        annotations:
          summary: "Potential Jenkins memory leak"
          description: "Jenkins memory usage increased by {{ $value | humanizeBytes }} in the last hour."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-memory-leak"

      # Plugin Alerts
      - alert: JenkinsPluginUpdateAvailable
        expr: jenkins_plugins_with_updates > 10
        for: 24h
        labels:
          severity: info
          service: jenkins
          category: maintenance
        annotations:
          summary: "Jenkins plugin updates available"
          description: "{{ $value }} Jenkins plugin updates are available."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-plugin-updates"

      - alert: JenkinsSecurityUpdateAvailable
        expr: jenkins_plugins_with_security_updates > 0
        for: 1h
        labels:
          severity: warning
          service: jenkins
          category: security
        annotations:
          summary: "Jenkins security updates available"
          description: "{{ $value }} Jenkins plugins have security updates available."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-security-updates"

      # Backup Alerts
      - alert: JenkinsBackupFailed
        expr: jenkins_backup_last_success_timestamp < (time() - 86400)
        for: 1h
        labels:
          severity: critical
          service: jenkins
          category: backup
        annotations:
          summary: "Jenkins backup failed"
          description: "Jenkins backup hasn't succeeded in over 24 hours."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-backup-failure"

      - alert: JenkinsBackupOld
        expr: jenkins_backup_last_success_timestamp < (time() - 172800)  # 48 hours
        for: 1h
        labels:
          severity: warning
          service: jenkins
          category: backup
        annotations:
          summary: "Jenkins backup is old"
          description: "Last successful Jenkins backup was {{ $value | humanizeDuration }} ago."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-backup-old"

  - name: jenkins.build.alerts
    rules:
      # Build Duration Alerts
      - alert: JenkinsBuildTooLong
        expr: jenkins_builds_duration_milliseconds > 3600000  # 1 hour
        for: 5m
        labels:
          severity: warning
          service: jenkins
          category: performance
        annotations:
          summary: "Jenkins build taking too long"
          description: "Build {{ $labels.job }}#{{ $labels.number }} has been running for {{ $value | humanizeDuration }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-long-builds"

      - alert: JenkinsBuildStuck
        expr: jenkins_builds_duration_milliseconds > 7200000  # 2 hours
        for: 10m
        labels:
          severity: critical
          service: jenkins
          category: availability
        annotations:
          summary: "Jenkins build appears stuck"
          description: "Build {{ $labels.job }}#{{ $labels.number }} has been running for {{ $value | humanizeDuration }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-stuck-builds"

      # Build Rate Alerts
      - alert: JenkinsLowBuildRate
        expr: rate(jenkins_builds_total[1h]) < 0.1
        for: 30m
        labels:
          severity: warning
          service: jenkins
          category: monitoring
        annotations:
          summary: "Low Jenkins build rate"
          description: "Jenkins build rate is {{ $value }} builds per second over the last hour."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-low-build-rate"

      - alert: JenkinsNoBuildActivity
        expr: increase(jenkins_builds_total[2h]) == 0
        for: 2h
        labels:
          severity: warning
          service: jenkins
          category: monitoring
        annotations:
          summary: "No Jenkins build activity"
          description: "No builds have been triggered in the last 2 hours."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-no-builds"

  - name: jenkins.security.alerts
    rules:
      # Security Alerts
      - alert: JenkinsUnauthorizedAccess
        expr: increase(jenkins_http_requests_total{status=~"401|403"}[5m]) > 10
        for: 1m
        labels:
          severity: warning
          service: jenkins
          category: security
        annotations:
          summary: "Jenkins unauthorized access attempts"
          description: "{{ $value }} unauthorized access attempts in the last 5 minutes."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-security-breach"

      - alert: JenkinsHighErrorRate
        expr: (rate(jenkins_http_requests_total{status=~"5.."}[5m]) / rate(jenkins_http_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          service: jenkins
          category: availability
        annotations:
          summary: "High Jenkins error rate"
          description: "Jenkins error rate is {{ $value | humanizePercentage }} over the last 5 minutes."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-high-error-rate"

      - alert: JenkinsAdminLogin
        expr: increase(jenkins_admin_logins_total[1h]) > 0
        for: 1m
        labels:
          severity: info
          service: jenkins
          category: security
        annotations:
          summary: "Jenkins admin login detected"
          description: "{{ $value }} admin logins detected in the last hour."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-admin-access"

  - name: jenkins.integration.alerts
    rules:
      # Integration Alerts
      - alert: JenkinsGitConnectionFailed
        expr: increase(jenkins_git_connection_failures_total[10m]) > 5
        for: 2m
        labels:
          severity: warning
          service: jenkins
          category: integration
        annotations:
          summary: "Jenkins Git connection failures"
          description: "{{ $value }} Git connection failures in the last 10 minutes."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-git-issues"

      - alert: JenkinsDockerConnectionFailed
        expr: jenkins_docker_connection_status == 0
        for: 5m
        labels:
          severity: critical
          service: jenkins
          category: integration
        annotations:
          summary: "Jenkins Docker connection failed"
          description: "Jenkins cannot connect to Docker daemon."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-docker-issues"

      - alert: JenkinsKubernetesConnectionFailed
        expr: jenkins_kubernetes_connection_status == 0
        for: 5m
        labels:
          severity: critical
          service: jenkins
          category: integration
        annotations:
          summary: "Jenkins Kubernetes connection failed"
          description: "Jenkins cannot connect to Kubernetes cluster."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-k8s-issues"

      - alert: JenkinsSonarQubeConnectionFailed
        expr: jenkins_sonarqube_connection_status == 0
        for: 10m
        labels:
          severity: warning
          service: jenkins
          category: integration
        annotations:
          summary: "Jenkins SonarQube connection failed"
          description: "Jenkins cannot connect to SonarQube server."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-sonarqube-issues"

  - name: jenkins.maintenance.alerts
    rules:
      # Maintenance Alerts
      - alert: JenkinsOldVersion
        expr: jenkins_version_info{version!~"2\\.(4[0-9][0-9]|[5-9][0-9][0-9]).*"}
        for: 24h
        labels:
          severity: info
          service: jenkins
          category: maintenance
        annotations:
          summary: "Jenkins version is outdated"
          description: "Jenkins version {{ $labels.version }} should be updated."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-updates"

      - alert: JenkinsLogRotationNeeded
        expr: jenkins_log_size_bytes > 1073741824  # 1GB
        for: 1h
        labels:
          severity: warning
          service: jenkins
          category: maintenance
        annotations:
          summary: "Jenkins log rotation needed"
          description: "Jenkins log size is {{ $value | humanizeBytes }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-log-rotation"

      - alert: JenkinsWorkspaceCleanupNeeded
        expr: jenkins_workspace_size_bytes > 10737418240  # 10GB
        for: 6h
        labels:
          severity: info
          service: jenkins
          category: maintenance
        annotations:
          summary: "Jenkins workspace cleanup needed"
          description: "Jenkins workspace size is {{ $value | humanizeBytes }}."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-workspace-cleanup"

      - alert: JenkinsTempFilesHigh
        expr: jenkins_temp_files_count > 1000
        for: 1h
        labels:
          severity: warning
          service: jenkins
          category: maintenance
        annotations:
          summary: "High number of Jenkins temp files"
          description: "{{ $value }} temporary files found in Jenkins workspace."
          runbook_url: "https://wiki.company.com/runbooks/jenkins-temp-cleanup"