server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://course-selling-platf-mysql-1:3307/courses_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://course-selling-platf-eureka-server-1:8761/eureka/
