server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://<prod-db-host>:3306/course_platform?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   
    show-sql: false

logging:
  level:
    org.springframework: WARN
    com.courseplatform: INFO

jwt:
  secret: ${APP_JWT_SECRET}   
  expiration: 86400000
