spring:
  application:
    name: user-management-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/course_platform

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
