spring:
  application:
    name: user-management-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mariadb:3306/course_platform
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
