spring:
  application:
    name: user-management-service
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql-db:3306/course_platform
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
