server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mariadb:3306/course_platform
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework: INFO
    com.courseplatform: DEBUG

jwt:
  secret: dev_secret_change_me
  expiration: 86400000
