server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: user-management-service

  datasource:
    url: jdbc:mysql://course-selling-platf-mysql-1:3307/${USER_SERVICE_DB_NAME:users_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USER_SERVICE_DB_USERNAME:root}
    password: ${USER_SERVICE_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:please_change_this}
    expiration: ${APP_JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: http://course-selling-platf-eureka-server-1:8761/eureka/
